import type { Metadata } from "next";
import { Jersey_25 } from "next/font/google";
import "./globals.css";

export const jersey = Jersey_25({
  weight: "400",
  variable: "--font-jersey",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jersey.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
